/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author A13003988
 */
public class VAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VAdministrador
     */
    public VAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VAnadirProducto = new javax.swing.JFrame();
        PanelAgregar = new javax.swing.JPanel();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextMarca = new javax.swing.JTextField();
        TextPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextPrecioCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        TextCantidad = new javax.swing.JTextField();
        BotonCancelarAnadir = new javax.swing.JButton();
        BotonAceptarAnadir = new javax.swing.JButton();
        VElegirOpcion = new javax.swing.JFrame();
        botonAgregar2 = new javax.swing.JButton();
        botonAumentar2 = new javax.swing.JButton();
        VAumentarProducto = new javax.swing.JFrame();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        botonAumentarProducto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonNewProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonRemoveProducto = new javax.swing.JButton();
        BotonReporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dispositivo", "Accesorio", "Software", "Otro" }));
        ComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese la categoria del producto");

        jLabel7.setText("Ingrese el nombre del producto:");

        jLabel8.setText("Ingrese la marca o compañía del producto");

        jLabel9.setText("Ingrese el precio de venta del producto");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Añadir producto");

        jLabel11.setText("Ingrese el precio de compra del producto");

        jLabel12.setText("Ingresa la descripción del artículo (opcional):");

        TextDescripcion.setColumns(20);
        TextDescripcion.setRows(5);
        jScrollPane1.setViewportView(TextDescripcion);

        jLabel13.setText("Ingresa la cantidad de artículos a añadir:");

        TextCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidadActionPerformed(evt);
            }
        });

        BotonCancelarAnadir.setText("Cancelar");

        BotonAceptarAnadir.setText("Aceptar");

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)
                        .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextNombre)
                        .addComponent(TextMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addComponent(TextPrecio)
                        .addComponent(jLabel7)
                        .addComponent(TextPrecioCompra))
                    .addComponent(TextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                        .addComponent(BotonAceptarAnadir)
                        .addGap(77, 77, 77)
                        .addComponent(BotonCancelarAnadir)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(188, 188, 188))))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelarAnadir)
                    .addComponent(BotonAceptarAnadir))
                .addContainerGap())
        );

        javax.swing.GroupLayout VAnadirProductoLayout = new javax.swing.GroupLayout(VAnadirProducto.getContentPane());
        VAnadirProducto.getContentPane().setLayout(VAnadirProductoLayout);
        VAnadirProductoLayout.setHorizontalGroup(
            VAnadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VAnadirProductoLayout.setVerticalGroup(
            VAnadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VAnadirProductoLayout.createSequentialGroup()
                .addComponent(PanelAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botonAgregar2.setText("AGREGAR NUEVO PRODUCTO");
        botonAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar2ActionPerformed(evt);
            }
        });

        botonAumentar2.setText("AUMENTAR PRODUCTO EXISTENTE");

        javax.swing.GroupLayout VElegirOpcionLayout = new javax.swing.GroupLayout(VElegirOpcion.getContentPane());
        VElegirOpcion.getContentPane().setLayout(VElegirOpcionLayout);
        VElegirOpcionLayout.setHorizontalGroup(
            VElegirOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VElegirOpcionLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(VElegirOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAumentar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        VElegirOpcionLayout.setVerticalGroup(
            VElegirOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VElegirOpcionLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(botonAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(botonAumentar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Elige el producto a aumentar unidades");

        botonAumentarProducto.setText("AUMENTAR");

        jLabel15.setText("Ingresa la cantidad de articulos a aumentar:");

        javax.swing.GroupLayout VAumentarProductoLayout = new javax.swing.GroupLayout(VAumentarProducto.getContentPane());
        VAumentarProducto.getContentPane().setLayout(VAumentarProductoLayout);
        VAumentarProductoLayout.setHorizontalGroup(
            VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VAumentarProductoLayout.createSequentialGroup()
                .addGroup(VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VAumentarProductoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VAumentarProductoLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VAumentarProductoLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VAumentarProductoLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(botonAumentarProducto)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        VAumentarProductoLayout.setVerticalGroup(
            VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VAumentarProductoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(botonAumentarProducto)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Control administrativo de TechnoShop");

        BotonNewProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconoAñadir.png"))); // NOI18N
        BotonNewProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNewProductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Bienvenido: ¿Que desea usted hacer?");

        BotonRemoveProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bag-remove.jpg"))); // NOI18N

        BotonReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reporticon.jpg"))); // NOI18N

        jLabel3.setText("Añadir un nuevo producto");

        jLabel4.setText("Retirar un producto existente");

        jLabel5.setText("Generar un reporte");

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonRemoveProducto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonSalir)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRemoveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNewProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNewProductoActionPerformed
        // TODO add your handling code here:
        PanelAgregar.setVisible(true);
        PanelAgregar.setBounds(478, 617, 478, 617);
    }//GEN-LAST:event_BotonNewProductoActionPerformed

    private void ComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCategoriaActionPerformed

    private void TextCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidadActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregar2ActionPerformed
  
    public JButton getBotonAceptar() {
        return BotonAceptarAnadir;
    }

    public void setBotonAceptar(JButton BotonAceptar) {
        this.BotonAceptarAnadir = BotonAceptar;
    }

    public JButton getBotonCancelar() {
        return BotonCancelarAnadir;
    }

    public void setBotonCancelar(JButton BotonCancelar) {
        this.BotonCancelarAnadir = BotonCancelar;
    }

    public JComboBox<String> getComboBoxCategoria() {
        return ComboBoxCategoria;
    }

    public void setComboBoxCategoria(JComboBox<String> ComboBoxCategoria) {
        this.ComboBoxCategoria = ComboBoxCategoria;
    }

    public JTextField getTextCantidad() {
        return TextCantidad;
    }

    public void setTextCantidad(JTextField TextCantidad) {
        this.TextCantidad = TextCantidad;
    }

    public JTextArea getTextDescripcion() {
        return TextDescripcion;
    }

    public void setTextDescripcion(JTextArea TextDescripcion) {
        this.TextDescripcion = TextDescripcion;
    }

    public JTextField getTextMarca() {
        return TextMarca;
    }

    public void setTextMarca(JTextField TextMarca) {
        this.TextMarca = TextMarca;
    }

    public JTextField getTextNombre() {
        return TextNombre;
    }

    public void setTextNombre(JTextField TextNombre) {
        this.TextNombre = TextNombre;
    }

    public JTextField getTextPrecio() {
        return TextPrecio;
    }

    public void setTextPrecio(JTextField TextPrecio) {
        this.TextPrecio = TextPrecio;
    }

    public JTextField getTextPrecioCompra() {
        return TextPrecioCompra;
    }

    public void setTextPrecioCompra(JTextField TextPrecioCompra) {
        this.TextPrecioCompra = TextPrecioCompra;
    }

    public JButton getBotonNewProducto() {
        return BotonNewProducto;
    }

    public void setBotonNewProducto(JButton BotonNewProducto) {
        this.BotonNewProducto = BotonNewProducto;
    }

    public JButton getBotonRemoveProducto() {
        return BotonRemoveProducto;
    }

    public void setBotonRemoveProducto(JButton BotonRemoveProducto) {
        this.BotonRemoveProducto = BotonRemoveProducto;
    }

    public JButton getBotonReporte() {
        return BotonReporte;
    }

    public void setBotonReporte(JButton BotonReporte) {
        this.BotonReporte = BotonReporte;
    }

    public JPanel getPanelAgregar() {
        return PanelAgregar;
    }

    public void setPanelAgregar(JPanel PanelAgregar) {
        this.PanelAgregar = PanelAgregar;
    }

    public JButton getBotonSalir() {
        return BotonSalir;
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptarAnadir;
    private javax.swing.JButton BotonCancelarAnadir;
    private javax.swing.JButton BotonNewProducto;
    private javax.swing.JButton BotonRemoveProducto;
    private javax.swing.JButton BotonReporte;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JTextField TextCantidad;
    private javax.swing.JTextArea TextDescripcion;
    private javax.swing.JTextField TextMarca;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextPrecio;
    private javax.swing.JTextField TextPrecioCompra;
    private javax.swing.JFrame VAnadirProducto;
    private javax.swing.JFrame VAumentarProducto;
    private javax.swing.JFrame VElegirOpcion;
    private javax.swing.JButton botonAgregar2;
    private javax.swing.JButton botonAumentar2;
    private javax.swing.JButton botonAumentarProducto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCantidad;
    // End of variables declaration//GEN-END:variables
}
