/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author A13003988
 */
public class VAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VAdministrador
     */
    public VAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VAnadirProducto = new javax.swing.JFrame();
        PanelAgregar = new javax.swing.JPanel();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextMarca = new javax.swing.JTextField();
        TextPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextPrecioCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        TextCantidad = new javax.swing.JTextField();
        BotonCancelar = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        VAnadirProducto2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        botonAnadirProducto2 = new javax.swing.JButton();
        botonAnadirExistente = new javax.swing.JButton();
        VAumentarProducto = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        botonAumentar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        textAumentar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaAumentarProductos = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        botonVolverAumentarProducto = new javax.swing.JButton();
        VModificaProducto = new javax.swing.JFrame();
        botonRegresarModificar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        textModifId = new javax.swing.JTextField();
        textModifPrecioCompra = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        comboBoxModifCategoria = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textModifDescripcion = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        textModifNombre = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        textModifMarca = new javax.swing.JTextField();
        textModifPrecioVenta = new javax.swing.JTextField();
        botonAceptarModif = new javax.swing.JButton();
        comboBoxModificar = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        botonMostrarModifProducto = new javax.swing.JButton();
        VRetirarProducto = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        botonRetirar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        botonRetirarVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotonNewProducto = new javax.swing.JButton();
        labelBienvenida = new javax.swing.JLabel();
        BotonRemoveProducto = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dispositivo", "Accesorio", "Software", "Otro" }));
        ComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese la categoria del producto");

        jLabel7.setText("Ingrese el id del producto");

        jLabel8.setText("Ingrese la marca o compañía del producto");

        jLabel9.setText("Ingrese el precio de venta del producto");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Añadir producto");

        jLabel11.setText("Ingrese el precio de compra del producto");

        jLabel12.setText("Ingresa la descripción del artículo (opcional):");

        TextDescripcion.setColumns(20);
        TextDescripcion.setRows(5);
        jScrollPane1.setViewportView(TextDescripcion);

        jLabel13.setText("Ingresa la cantidad de artículos a añadir:");

        TextCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidadActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        jLabel16.setText("Ingrese el nombre del producto");

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(TextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(TextPrecio)
                                .addComponent(jLabel7)
                                .addComponent(TextPrecioCompra)
                                .addComponent(jLabel8)
                                .addComponent(jLabel16))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(BotonAceptar)
                        .addGap(75, 75, 75)
                        .addComponent(BotonCancelar)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(193, 193, 193))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel16)
                .addGap(11, 11, 11)
                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptar)
                    .addComponent(BotonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VAnadirProductoLayout = new javax.swing.GroupLayout(VAnadirProducto.getContentPane());
        VAnadirProducto.getContentPane().setLayout(VAnadirProductoLayout);
        VAnadirProductoLayout.setHorizontalGroup(
            VAnadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VAnadirProductoLayout.setVerticalGroup(
            VAnadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VAnadirProductoLayout.createSequentialGroup()
                .addComponent(PanelAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botonAnadirProducto2.setText("AGREGAR NUEVO PRODUCTO");
        botonAnadirProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirProducto2ActionPerformed(evt);
            }
        });

        botonAnadirExistente.setText("AGREGAR PRODUCTO EXISTENTE");
        botonAnadirExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirExistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAnadirExistente, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(botonAnadirProducto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(botonAnadirProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(botonAnadirExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout VAnadirProducto2Layout = new javax.swing.GroupLayout(VAnadirProducto2.getContentPane());
        VAnadirProducto2.getContentPane().setLayout(VAnadirProducto2Layout);
        VAnadirProducto2Layout.setHorizontalGroup(
            VAnadirProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VAnadirProducto2Layout.setVerticalGroup(
            VAnadirProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setText("Selecciona el articulo que desees aumentar unidades");

        botonAumentar.setText("AUMENTAR");
        botonAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAumentarActionPerformed(evt);
            }
        });

        jLabel15.setText("Introduce las unidades");

        tablaAumentarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaAumentarProductos);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("AGREGAR NUEVAS UNIDADES");

        botonVolverAumentarProducto.setText("VOLVER");

        javax.swing.GroupLayout VAumentarProductoLayout = new javax.swing.GroupLayout(VAumentarProducto.getContentPane());
        VAumentarProducto.getContentPane().setLayout(VAumentarProductoLayout);
        VAumentarProductoLayout.setHorizontalGroup(
            VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VAumentarProductoLayout.createSequentialGroup()
                .addGroup(VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VAumentarProductoLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(botonAumentar)
                        .addGap(199, 199, 199)
                        .addComponent(botonVolverAumentarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VAumentarProductoLayout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(VAumentarProductoLayout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addComponent(jLabel17))
                        .addGroup(VAumentarProductoLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(VAumentarProductoLayout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addGroup(VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        VAumentarProductoLayout.setVerticalGroup(
            VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VAumentarProductoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(VAumentarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolverAumentarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        botonRegresarModificar.setText("Regresar");
        botonRegresarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarModificarActionPerformed(evt);
            }
        });

        jLabel18.setText("Ingrese el precio de venta del producto");

        jLabel19.setText("Ingrese el nombre del producto");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Modificar producto");

        jLabel21.setText("Ingrese el precio de compra del producto");

        comboBoxModifCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dispositivo", "Accesorio", "Software", "Otro" }));
        comboBoxModifCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModifCategoriaActionPerformed(evt);
            }
        });

        jLabel22.setText("Ingresa la descripción del artículo (opcional):");

        jLabel23.setText("Ingrese la categoria del producto");

        textModifDescripcion.setColumns(20);
        textModifDescripcion.setRows(5);
        jScrollPane2.setViewportView(textModifDescripcion);

        jLabel24.setText("ID:");

        jLabel26.setText("Ingrese la marca o compañía del producto");

        botonAceptarModif.setText("Aceptar");
        botonAceptarModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarModifActionPerformed(evt);
            }
        });

        comboBoxModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel27.setText("Selecciona el producto a modificar:");

        botonMostrarModifProducto.setText("Mostrar");

        javax.swing.GroupLayout VModificaProductoLayout = new javax.swing.GroupLayout(VModificaProducto.getContentPane());
        VModificaProducto.getContentPane().setLayout(VModificaProductoLayout);
        VModificaProductoLayout.setHorizontalGroup(
            VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VModificaProductoLayout.createSequentialGroup()
                .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VModificaProductoLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel20))
                    .addGroup(VModificaProductoLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VModificaProductoLayout.createSequentialGroup()
                .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VModificaProductoLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(comboBoxModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMostrarModifProducto))
                    .addGroup(VModificaProductoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VModificaProductoLayout.createSequentialGroup()
                                .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel23)
                                        .addComponent(comboBoxModifCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textModifMarca)
                                        .addComponent(textModifPrecioVenta)
                                        .addComponent(textModifPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel19)
                                        .addGroup(VModificaProductoLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textModifNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textModifId, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VModificaProductoLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(botonAceptarModif, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonRegresarModificar)
                                .addGap(33, 33, 33)))))
                .addGap(59, 59, 59))
        );
        VModificaProductoLayout.setVerticalGroup(
            VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VModificaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrarModifProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textModifId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel19)
                .addGap(11, 11, 11)
                .addComponent(textModifNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textModifMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxModifCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textModifPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textModifPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(VModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresarModificar)
                    .addComponent(botonAceptarModif, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Selecciona el producto para retirar");

        botonRetirar.setText("RETIRAR DE VENTA");
        botonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetirarActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaProductos);

        botonRetirarVolver.setText("VOLVER");

        javax.swing.GroupLayout VRetirarProductoLayout = new javax.swing.GroupLayout(VRetirarProducto.getContentPane());
        VRetirarProducto.getContentPane().setLayout(VRetirarProductoLayout);
        VRetirarProductoLayout.setHorizontalGroup(
            VRetirarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VRetirarProductoLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VRetirarProductoLayout.createSequentialGroup()
                .addGroup(VRetirarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VRetirarProductoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VRetirarProductoLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(botonRetirar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(botonRetirarVolver)))
                .addGap(76, 76, 76))
        );
        VRetirarProductoLayout.setVerticalGroup(
            VRetirarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VRetirarProductoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(VRetirarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRetirarVolver))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Control administrativo de TechnoShop");

        BotonNewProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconoAñadir.png"))); // NOI18N
        BotonNewProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNewProductoActionPerformed(evt);
            }
        });

        labelBienvenida.setText("Bienvenido: ¿Que desea usted hacer?");

        BotonRemoveProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bag-remove.jpg"))); // NOI18N
        BotonRemoveProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRemoveProductoActionPerformed(evt);
            }
        });

        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reporticon.jpeg"))); // NOI18N
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        jLabel3.setText("Añadir un nuevo producto");

        jLabel4.setText("Retirar un producto existente");

        jLabel5.setText("Modificar un producto");

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotonRemoveProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(labelBienvenida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonSalir)))
                .addGap(18, 18, 18)
                .addComponent(labelBienvenida)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRemoveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNewProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNewProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNewProductoActionPerformed

    private void ComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCategoriaActionPerformed

    private void TextCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidadActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonRegresarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarModificarActionPerformed

    private void botonAnadirExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirExistenteActionPerformed

    }//GEN-LAST:event_botonAnadirExistenteActionPerformed

    private void botonAnadirProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirProducto2ActionPerformed

    }//GEN-LAST:event_botonAnadirProducto2ActionPerformed

    private void botonAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAumentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAumentarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void botonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRetirarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonRemoveProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRemoveProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRemoveProductoActionPerformed

    private void comboBoxModifCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModifCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxModifCategoriaActionPerformed

    private void botonAceptarModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptarModifActionPerformed
    /**
     * Metodo que devuelve el boton de aceptar
     * @return BotonAceptar devuelve el boton
     */  
    public JButton getBotonAceptar() {
        return BotonAceptar;
    }
    /**
     * Metodo que define el boton de aceptar
     * @param BotonAceptar nombre del parametro que recibe el boton
     */
    public void setBotonAceptar(JButton BotonAceptar) {
        this.BotonAceptar = BotonAceptar;
    }
    /**
     * Metodo que devuelve el boton de cancelar
     * @return BotonCancelar devuelve el boton
     */
    public JButton getBotonCancelar() {
        return BotonCancelar;
    }
    /**
     * Metodo que devuelve el boton de anadir un producto ya existente
     * @return botonAnadirExistente devuelve el boton
     */
    public JButton getBotonAnadirExistente(){
        return botonAnadirExistente;
    }
    /**
     * Anade productos
     * @return botonAnadirProducto2
     */
    public JButton getBotonAnadirProducto2(){
        return botonAnadirProducto2;
    }    
    /**
     * @deprecated 
     * @param BotonCancelar 
     */
    public void setBotonCancelar(JButton BotonCancelar) {
        this.BotonCancelar = BotonCancelar;
    }
    /**
     * Metodo que llama al comboBox de categoria
     * @return ComboBoxCategoria devuelve el combo BOX
     */
    public JComboBox<String> getComboBoxCategoria() {
        return ComboBoxCategoria;
    }
    /**
     * Metodo que define el combo box categoria 
     * @param ComboBoxCategoria parametro del combo box
     */
    public void setComboBoxCategoria(JComboBox<String> ComboBoxCategoria) {
        this.ComboBoxCategoria = ComboBoxCategoria;
    }
    /**
     * Metodo que recive la cantidad de productos
     * @return TextCantidad devuelve la cantidad del textfield
     */
    public JTextField getTextCantidad() {
        return TextCantidad;
    }
    /**
     * Metodo que define la cantidad 
     * @param TextCantidad parametro que recibe el textfield
     */
    public void setTextCantidad(JTextField TextCantidad) {
        this.TextCantidad = TextCantidad;
    }
    /**
     * Metodo que recibe la descripcion del producto de acuerdo al administrador
     * en una JtextArea
     * @return TextDescripcion devuelve un JtextArea
     */
    public JTextArea getTextDescripcion() {
        return TextDescripcion;
    }
    /**
     * Metodo que define la descripcion del producto en la JTextArea
     * @param TextDescripcion parametro que recibe el JTextArea
     */
    public void setTextDescripcion(JTextArea TextDescripcion) {
        this.TextDescripcion = TextDescripcion;
    }
    /**
     * Metodo que recibe la marca
     * @return devuelve la marca
     */
    public JTextField getTextMarca() {
        return TextMarca;
    }
    /**
     * Metodo que recibe el nombre
     * @return TextNombre devuelve el nombre
     */
    public JTextField getTextNombre() {
        return TextNombre;
    }
    /**
     * Metodo que recibe el precio
     * @return TextPrecio devuelve el precio
     */
    public JTextField getTextPrecio() {
        return TextPrecio;
    }
    /**
     * Metodo que recibe el precio de compra
     * @return TextPrecioCompra devuelve el precio de compra 
     */
    public JTextField getTextPrecioCompra() {
        return TextPrecioCompra;
    }
    /**
     * metodo que recibe el boton de agregar un nuevo producto por parte
     * del administrador
     * @return BotonNewProducto devuelve el boton
     */
    public JButton getBotonNewProducto() {
        return BotonNewProducto;
    }
    /**
     * Anade producto
     * @return VAnadirProducto lo devuelve
     */
    public JFrame getVAnadirProducto() {
        return VAnadirProducto;
    }
    /**
     * Anade Producto
     * @return VAnadirProducto lo devuelve
     */
    public JFrame getVAnadirProducto2() {
        return VAnadirProducto2;
    }
    /**
     * Metodo que te deja aumentar producto por parte del administrador
     * @return VAumentarProducto devuelve la funcion
     */
    public JFrame getVAumentarProducto() {
        return VAumentarProducto;
    }
    /**
     * Metodo que te deja reducir producto por parte del administraodr
     * @return BotonRemoveProducto devuelve la funcion
     */
    public JButton getBotonRemoveProducto() {
        return BotonRemoveProducto;
    }
    /**
     * Modifica
     * @return botonModificar devuelve un boton
     */
    public JButton getBotonModificar() {
        return botonModificar;
    }
    /**
     * Agrega
     * @return PanelAgregar devuelve esto
     */
    public JPanel getPanelAgregar() {
        return PanelAgregar;
    }
    /**
     * Metodo cuando el administrador selecciona el boton de salir
     * @return BotonSalir devuelve un boton
     */
    public JButton getBotonSalir() {
        return BotonSalir;
    }
    /**
     * Metodo cuando en el label sale la pantalla de bienvenida cuando
     * ingresa exitosamente
     * @return labelBienvenida devuelve un label
     */
    public JLabel getLabelBienvenida(){
        return labelBienvenida;
    }
    /**
     * Aumenta producto
     * @return textAumentar
     */
    public JTextField getTextAumentar(){
        return textAumentar;
    }
    /**
     * Aumenta producto
     * @return botonAumentar
     */
    public JButton getBotonAumentar() {
        return botonAumentar;
    }
    /**
     * metodo que muestra la tabla de productos
     * @return tablaProductos devuelve esta tabla
     */
    public JTable getTablaProductos(){
        return tablaProductos;
    }
    /**
     * metodo retirar volver
     * @return botonRetirarVolver
     */
    public JButton getBotonRetirarVolver(){
        return botonRetirarVolver;
    }
    /**
     * Metodo del boton regresar
     * @return botonRegresarModificar devuelve un boton
     */
    public JButton getBotonRegresar() {
        return botonRegresarModificar;
    }
    /**
     * Muestra el reporte de ventas de la tienda
     * @return VModificaProducto
     */
    public JFrame getVReporte() {
        return VModificaProducto;
    }
    /**
     * Remueve producto
     * @return VRetirarProducto
     */
    public JFrame getVRemover() {
        return VRetirarProducto;
    }
    /**
     * Remueve producro
     * @return botonRetirar
     */
    public JButton getBotonRetirar() {
        return botonRetirar;
    }
    /**
     * Recibe el id
     * @return Textid
     */
    public JTextField getTextId() {
        return TextId;
    }
    /**
     * Aumenta y muestra tabla productos por peticion del administrador
     * @return tablaAumentarProductos
     */
    public JTable getTablaAumentarProductos(){
        return tablaAumentarProductos;
    }   
    /**
     * Metodo que define boton
     * @return bptonVolverAumentarProducto
     */
    public JButton getBotonVolverAumentarProductos(){
        return botonVolverAumentarProducto;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonNewProducto;
    private javax.swing.JButton BotonRemoveProducto;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JTextField TextCantidad;
    private javax.swing.JTextArea TextDescripcion;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextMarca;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextPrecio;
    private javax.swing.JTextField TextPrecioCompra;
    private javax.swing.JFrame VAnadirProducto;
    private javax.swing.JFrame VAnadirProducto2;
    private javax.swing.JFrame VAumentarProducto;
    private javax.swing.JFrame VModificaProducto;
    private javax.swing.JFrame VRetirarProducto;
    private javax.swing.JButton botonAceptarModif;
    private javax.swing.JButton botonAnadirExistente;
    public javax.swing.JButton botonAnadirProducto2;
    private javax.swing.JButton botonAumentar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonMostrarModifProducto;
    private javax.swing.JButton botonRegresarModificar;
    private javax.swing.JButton botonRetirar;
    private javax.swing.JButton botonRetirarVolver;
    private javax.swing.JButton botonVolverAumentarProducto;
    private javax.swing.JComboBox<String> comboBoxModifCategoria;
    private javax.swing.JComboBox<String> comboBoxModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JTable tablaAumentarProductos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField textAumentar;
    private javax.swing.JTextArea textModifDescripcion;
    private javax.swing.JTextField textModifId;
    private javax.swing.JTextField textModifMarca;
    private javax.swing.JTextField textModifNombre;
    private javax.swing.JTextField textModifPrecioCompra;
    private javax.swing.JTextField textModifPrecioVenta;
    // End of variables declaration//GEN-END:variables

    public JFrame getVModificaProducto() {
        return VModificaProducto;
    }

    public JButton getBotonAceptarModif() {
        return botonAceptarModif;
    }

    public JButton getBotonMostrarModifProducto() {
        return botonMostrarModifProducto;
    }

    public JButton getBotonRegresarModificar() {
        return botonRegresarModificar;
    }

    public JButton getBotonVolverAumentarProducto() {
        return botonVolverAumentarProducto;
    }

    public JComboBox<String> getComboBoxModifCategoria() {
        return comboBoxModifCategoria;
    }

    public JComboBox<String> getComboBoxModificar() {
        return comboBoxModificar;
    }

    public JTextArea getTextModifDescripcion() {
        return textModifDescripcion;
    }

    public JTextField getTextModifId() {
        return textModifId;
    }

    public JTextField getTextModifMarca() {
        return textModifMarca;
    }

    public JTextField getTextModifNombre() {
        return textModifNombre;
    }

    public JTextField getTextModifPrecioCompra() {
        return textModifPrecioCompra;
    }

    public JTextField getTextModifPrecioVenta() {
        return textModifPrecioVenta;
    }

}
