/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modelo.Usuario;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Juan D.M
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form VHome
     */
    
    public VHome(){
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonSesion = new javax.swing.JButton();
        BotonRegistrese = new javax.swing.JButton();
        BotonAdministrador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonDevice = new javax.swing.JButton();
        BotonAccesory = new javax.swing.JButton();
        BotonSoftware = new javax.swing.JButton();
        labelBienvenida = new javax.swing.JLabel();
        botonPedidos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTop5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Title.jpg"))); // NOI18N

        BotonSesion.setText("Iniciar Sesion");

        BotonRegistrese.setText("Registrarse");
        BotonRegistrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistreseActionPerformed(evt);
            }
        });

        BotonAdministrador.setText("Administrar Tienda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("           Categorias");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Top 5 productos mas vendidos");

        BotonDevice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DeviceIcon.jpg"))); // NOI18N
        BotonDevice.setText("Dispositivos");
        BotonDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeviceActionPerformed(evt);
            }
        });

        BotonAccesory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AccesoryIcon.jpg"))); // NOI18N
        BotonAccesory.setText("Accesorios");
        BotonAccesory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoryActionPerformed(evt);
            }
        });

        BotonSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SoftwareIcon.jpg"))); // NOI18N
        BotonSoftware.setText("Software");
        BotonSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSoftwareActionPerformed(evt);
            }
        });

        botonPedidos.setText("Mis pedidos");

        tablaTop5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Producto"
            }
        ));
        jScrollPane2.setViewportView(tablaTop5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372)
                        .addComponent(BotonRegistrese, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPedidos)
                    .addComponent(BotonSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BotonAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonAccesory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAdministrador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonSesion)
                            .addComponent(BotonRegistrese))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPedidos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAccesory, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDeviceActionPerformed

    private void BotonAccesoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAccesoryActionPerformed

    private void BotonRegistreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistreseActionPerformed

    private void BotonSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSoftwareActionPerformed

    public JButton getBotonAccesory() {
        return BotonAccesory;
    }

    public void setBotonAccesory(JButton BotonAccesory) {
        this.BotonAccesory = BotonAccesory;
    }

    public JButton getBotonAdministrador() {
        return BotonAdministrador;
    }

    public void setBotonAdministrador(JButton BotonAdministrador) {
        this.BotonAdministrador = BotonAdministrador;
    }

    public JButton getBotonDevice() {
        return BotonDevice;
    }

    public void setBotonDevice(JButton BotonDevice) {
        this.BotonDevice = BotonDevice;
    }

    public JButton getBotonRegistrese() {
        return BotonRegistrese;
    }

    public void setBotonRegistrese(JButton BotonRegistrese) {
        this.BotonRegistrese = BotonRegistrese;
    }

    public JButton getBotonSesion() {
        return BotonSesion;
    }

    public void setBotonSesion(JButton BotonSesion) {
        this.BotonSesion = BotonSesion;
    }

    public JButton getBotonSoftware() {
        return BotonSoftware;
    }

    public void setBotonSoftware(JButton BotonSoftware) {
        this.BotonSoftware = BotonSoftware;
    }
    
    public JLabel getLabelBienvenida(){
        return labelBienvenida;
    }
    public JButton getBotonPedidos(){
        return botonPedidos;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAccesory;
    private javax.swing.JButton BotonAdministrador;
    private javax.swing.JButton BotonDevice;
    private javax.swing.JButton BotonRegistrese;
    private javax.swing.JButton BotonSesion;
    private javax.swing.JButton BotonSoftware;
    private javax.swing.JButton botonPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JTable tablaTop5;
    // End of variables declaration//GEN-END:variables
}
