/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author Juan D.M
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form VHome
     */
    
    public VHome(){
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VMisPedidos = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        comboBoxPedidos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPedido = new javax.swing.JTextPane();
        botonVerPedido = new javax.swing.JButton();
        botonVolverPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotonSesion = new javax.swing.JButton();
        BotonRegistrese = new javax.swing.JButton();
        BotonAdministrador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonDevice = new javax.swing.JButton();
        BotonAccesory = new javax.swing.JButton();
        BotonSoftware = new javax.swing.JButton();
        labelBienvenida = new javax.swing.JLabel();
        botonPedidos = new javax.swing.JButton();
        botonVerCarrito = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        botonVerMembresia = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Mis Pedidos");

        comboBoxPedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(textPedido);

        botonVerPedido.setText("Ver");

        botonVolverPedidos.setText("Volver");

        javax.swing.GroupLayout VMisPedidosLayout = new javax.swing.GroupLayout(VMisPedidos.getContentPane());
        VMisPedidos.getContentPane().setLayout(VMisPedidosLayout);
        VMisPedidosLayout.setHorizontalGroup(
            VMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VMisPedidosLayout.createSequentialGroup()
                .addGroup(VMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VMisPedidosLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VMisPedidosLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(comboBoxPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(botonVerPedido))
                    .addGroup(VMisPedidosLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VMisPedidosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonVolverPedidos)
                .addGap(83, 83, 83))
        );
        VMisPedidosLayout.setVerticalGroup(
            VMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VMisPedidosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(VMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerPedido))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonVolverPedidos)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Title.jpg"))); // NOI18N

        BotonSesion.setText("Iniciar Sesion");

        BotonRegistrese.setText("Registrarse");
        BotonRegistrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistreseActionPerformed(evt);
            }
        });

        BotonAdministrador.setText("Administrar Tienda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("           Categorias");

        BotonDevice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DeviceIcon.jpg"))); // NOI18N
        BotonDevice.setText("Dispositivos");
        BotonDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeviceActionPerformed(evt);
            }
        });

        BotonAccesory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AccesoryIcon.jpg"))); // NOI18N
        BotonAccesory.setText("Accesorios");
        BotonAccesory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoryActionPerformed(evt);
            }
        });

        BotonSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SoftwareIcon.jpg"))); // NOI18N
        BotonSoftware.setText("Software");
        BotonSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSoftwareActionPerformed(evt);
            }
        });

        botonPedidos.setText("Mis pedidos");
        botonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedidosActionPerformed(evt);
            }
        });

        botonVerCarrito.setText("Ver Carrito");

        botonCerrarSesion.setText("Cerrar sesion");

        botonVerMembresia.setText("Ver Membresia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(186, 186, 186))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BotonAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonRegistrese, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(413, 413, 413)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonVerCarrito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(botonCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotonSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAccesory, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BotonDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonAccesory, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistrese, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVerCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(botonVerMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDeviceActionPerformed

    private void BotonAccesoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAccesoryActionPerformed

    private void BotonRegistreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistreseActionPerformed

    private void BotonSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSoftwareActionPerformed

    private void botonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPedidosActionPerformed
     /**
     * Metodo con el que se obtiene el boton BotonAccesory
     * @return Devuelve el boton BotonAccesory
     */
    public JButton getBotonAccesory() {
        return BotonAccesory;
    }

    
     /**
     * Metodo con el que se obtiene el boton BotonAdministrador
     * @return Devuelve el boton BotonAdministrador
     */
    public JButton getBotonAdministrador() {
        return BotonAdministrador;
    }
     /**
     * Metodo con el que se obtiene el boton BotonDevice
     * @return Devuelve el boton BotonDevice
     */
    
    public JButton getBotonDevice() {
        return BotonDevice;
    }

     /**
     * Metodo con el que se obtiene el boton BotonRegistrese
     * @return Devuelve el boton BotonRegistrese
     */

    public JButton getBotonRegistrese() {
        return BotonRegistrese;
    }
     /**
     * Metodo con el que se obtiene el boton BotonVolverPedidos
     * @return Devuelve el boton BotonVolverPedidos
     */
    public JButton getBotonVolverPedidos() {
        return botonVolverPedidos;
    }
     /**
     * Metodo con el que se obtiene el FRame VMisPedisos
     * @return Devuelve el Frame VMisPedidos
     */
    public JFrame getVMisPedidos() {
        return VMisPedidos;
    }
     /**
     * Metodo con el que se obtiene el boton BotonVerPedido
     * @return Devuelve el boton BotonVerPedido
     */
    public JButton getBotonVerPedido() {
        return botonVerPedido;
    }
     /**
     * Metodo con el que se obtiene el combobox ComboBoxPedidos
     * @return Devuelve el combobox ComboBoxPedidos
     */
    public JComboBox<String> getComboBoxPedidos() {
        return comboBoxPedidos;
    }
     /**
     * Metodo con el que se obtiene el TextPane TextPedido
     * @return Devuelve el TextPane TextPedido
     */
    public JTextPane getTextPedido() {
        return textPedido;
    }

    
    /**
     * Metodo con el que se obtiene el boton BotonSesion
     * @return Devuelve el boton BotonSesion
     */
    public JButton getBotonSesion() {
        return BotonSesion;
    }

    /**
     * Metodo con el que se obtiene el boton BotonSoftware
     * @return Devuelve el boton BotonSoftware
     */

    public JButton getBotonSoftware() {
        return BotonSoftware;
    }

      /**
     * Metodo con el que se obtiene el label LabelBienvenida
     * @return Devuelve el label LabelBienvenida
     */
    
    public JLabel getLabelBienvenida(){
        return labelBienvenida;
    }
      /**
     * Metodo con el que se obtiene el boton BotonPedidos
     * @return Devuelve el boton BotonPedidos
     */
    public JButton getBotonPedidos(){
        return botonPedidos;
    }
      /**
     * Metodo con el que se obtiene el boton BotonCerrarSesion
     * @return Devuelve el boton BotonCerrarSesion
     */
    public JButton getBotonCerrarSesion() {
        return botonCerrarSesion;
    }
      /**
     * Metodo con el que se obtiene el boton BotonVerCarrito
     * @return Devuelve el boton BotonVerCarrito
     */

    public JButton getBotonVerCarrito() {
        return botonVerCarrito;
    }
      /**
     * Metodo con el que se obtiene el boton BotonVerMembresia
     * @return Devuelve el boton botonVerMembresia
     */
    public JButton getBotonVerMembresia() {
        return botonVerMembresia;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAccesory;
    private javax.swing.JButton BotonAdministrador;
    private javax.swing.JButton BotonDevice;
    private javax.swing.JButton BotonRegistrese;
    private javax.swing.JButton BotonSesion;
    private javax.swing.JButton BotonSoftware;
    private javax.swing.JFrame VMisPedidos;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonPedidos;
    private javax.swing.JButton botonVerCarrito;
    private javax.swing.JButton botonVerMembresia;
    private javax.swing.JButton botonVerPedido;
    private javax.swing.JButton botonVolverPedidos;
    private javax.swing.JComboBox<String> comboBoxPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JTextPane textPedido;
    // End of variables declaration//GEN-END:variables

}
