/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modelo.Usuario;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Juan D.M
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form VHome
     */
    Usuario usuario = null;
    public VHome() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        botonPedidos.setVisible(false);
    }
    
    public VHome(Usuario usuario){
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.usuario = usuario;
        labelBienvenida.setText("Bienvenido "+ usuario.getNombre() +" "+ usuario.getApellido());
        System.out.println(usuario.getMembresia().getTipo()+"es mi tipo");
        BotonRegistrese.setVisible(false);
        BotonSesion.setVisible(false);
        botonPedidos.setVisible(true);
        BotonAdministrador.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonSesion = new javax.swing.JButton();
        BotonRegistrese = new javax.swing.JButton();
        BotonAdministrador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonDevice = new javax.swing.JButton();
        BotonAccesory = new javax.swing.JButton();
        BotonSoftware = new javax.swing.JButton();
        labelBienvenida = new javax.swing.JLabel();
        botonPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Title.jpg"))); // NOI18N

        BotonSesion.setText("Iniciar Sesion");

        BotonRegistrese.setText("Registrarse");
        BotonRegistrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistreseActionPerformed(evt);
            }
        });

        BotonAdministrador.setText("Administrar Tienda");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Categorias");

        jLabel3.setText("Top 5 productos mas vendidos");

        BotonDevice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DeviceIcon.jpg"))); // NOI18N
        BotonDevice.setText("Dispositivos");
        BotonDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeviceActionPerformed(evt);
            }
        });

        BotonAccesory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AccesoryIcon.jpg"))); // NOI18N
        BotonAccesory.setText("Accesorios");
        BotonAccesory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoryActionPerformed(evt);
            }
        });

        BotonSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SoftwareIcon.jpg"))); // NOI18N
        BotonSoftware.setText("Software");

        botonPedidos.setText("Mis pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(136, 136, 136))
                                .addComponent(BotonDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonAccesory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BotonRegistrese, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 96, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonPedidos)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonSesion)
                        .addComponent(BotonRegistrese)
                        .addComponent(BotonAdministrador)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonPedidos))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAccesory, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDeviceActionPerformed

    private void BotonAccesoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAccesoryActionPerformed

    private void BotonRegistreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistreseActionPerformed

    public JButton getBotonAccesory() {
        return BotonAccesory;
    }

    public void setBotonAccesory(JButton BotonAccesory) {
        this.BotonAccesory = BotonAccesory;
    }

    public JButton getBotonAdministrador() {
        return BotonAdministrador;
    }

    public void setBotonAdministrador(JButton BotonAdministrador) {
        this.BotonAdministrador = BotonAdministrador;
    }

    public JButton getBotonDevice() {
        return BotonDevice;
    }

    public void setBotonDevice(JButton BotonDevice) {
        this.BotonDevice = BotonDevice;
    }

    public JButton getBotonRegistrese() {
        return BotonRegistrese;
    }

    public void setBotonRegistrese(JButton BotonRegistrese) {
        this.BotonRegistrese = BotonRegistrese;
    }

    public JButton getBotonSesion() {
        return BotonSesion;
    }

    public void setBotonSesion(JButton BotonSesion) {
        this.BotonSesion = BotonSesion;
    }

    public JButton getBotonSoftware() {
        return BotonSoftware;
    }

    public void setBotonSoftware(JButton BotonSoftware) {
        this.BotonSoftware = BotonSoftware;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAccesory;
    private javax.swing.JButton BotonAdministrador;
    private javax.swing.JButton BotonDevice;
    private javax.swing.JButton BotonRegistrese;
    private javax.swing.JButton BotonSesion;
    private javax.swing.JButton BotonSoftware;
    private javax.swing.JButton botonPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBienvenida;
    // End of variables declaration//GEN-END:variables
}
