/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author Emmanuel
 */
public class VReporte extends javax.swing.JFrame {

    /**
     * Creates new form VGanancia
     */
    public VReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TReporte = new javax.swing.JTable();
        BMostrar = new javax.swing.JButton();
        BImprimir = new javax.swing.JButton();
        BRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Comp. escritorio Acer Aspire AC20-720-MB13", "$7,650", null, "", null},
                {"Laptop Asus  E402NA-GA002T    ", "$4,300", null, null, null},
                {"HP - Laptop 15-BW014LA   ", "$8,450", null, null, null},
                {"Smartphone Techpad M6    ", "$1,997", null, "", null},
                {"Apple - iPhone 8  ", "$16,500", null, null, null},
                {"Smartphone Motorola Moto C  ", " $1,600", null, null, null},
                {"Mouse Inalambrico M525", "$952", null, null, null},
                {"Teclado Bluetooth PC/Mac NEGRO AUDIOBAHN ", "$280", null, null, null},
                {"Teclado N. Laptop alámbrico USB marca AUDIOBAHN AKY60  ", "$118", null, null, null},
                {"Mouse óptico inalámbrico  USB AOM60 AUDIOBAHN AOM60  ", "$142", null, null, null},
                {"Juego DVD FIFA 16 ", "$300", null, null, null},
                {"Juego DVD Call of Duty Black Ops III", "$450 ", null, null, null},
                {"Juego DVD GTA V", "$800", null, null, null},
                {"Office 2016 Hogar y Estudiante Microsoft para PC 1  Equipo  ", "$2,000", null, null, null},
                {"Microsoft Mouse más Office 365 Personal Internet Security  ", "$1200", null, null, null}
            },
            new String [] {
                "Productos", "Precio", "Porcentaje/ganancia", "Total/Neto", "Total"
            }
        ));
        jScrollPane1.setViewportView(TReporte);

        BMostrar.setText("Mostrar");
        BMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMostrarActionPerformed(evt);
            }
        });

        BImprimir.setText("Imprimir");
        BImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BImprimirActionPerformed(evt);
            }
        });

        BRegresar.setText("Regresar");
        BRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(BMostrar)
                .addGap(42, 42, 42)
                .addComponent(BImprimir)
                .addGap(42, 42, 42)
                .addComponent(BRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMostrar)
                    .addComponent(BImprimir)
                    .addComponent(BRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BMostrarActionPerformed

    private void BImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BImprimirActionPerformed

    private void BRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRegresarActionPerformed

    public JButton getBImprimir() {
        return BImprimir;
    }

    public JButton getBMostrar() {
        return BMostrar;
    }

    public JButton getBRegresar() {
        return BRegresar;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BImprimir;
    private javax.swing.JButton BMostrar;
    private javax.swing.JButton BRegresar;
    private javax.swing.JTable TReporte;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
